# Generated by Django 3.1.2 on 2020-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('activity', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=100)),
            ],
        ),
    ]
