# Generated by Django 3.1.2 on 2020-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
