# Generated by Django 3.1.2 on 2020-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
