# Generated by Django 3.1.2 on 2020-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bipolar', '0002_auto_20201023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
