DEBUG: TRUE
SECRET_KEY: <SECRET-KEY>

DATABASE:
    HOST: 127.0.0.1
    NAME: <Name of PG Database>
    USER: <User having rights to that Database>
    PASSWORD: <Password of that user>
    PORT: <Port of PGSQL>

ALLOWED_HOSTS:
    - "127.0.0.1"
    - "localhost"
    - <list of ip addresses of all the servers>

GITHUB:
    REPO: <Path to local repository cloned from Heimdall-SSH-Keys>
    SECRET: <GitHub Webhook Secret>

SERVERSIDE:
    SECRET: <secret for Heimdall-serverside>

SLACK: <slack hook>
