DEBUG: (TRUE / FALSE)
USE_TZ: FALSE # DO NOT CHANGE
SECRET_KEY: # A fifty character key used by Django for hashing

DATABASE:
    HOST: db # DO NOT CHANGE
    NAME: # The name of the database which stores the logs
    USER: # The user having rights to the database
    PASSWORD: # Password for the user
    PORT: # Port on which the database container is listening

ALLOWED_HOSTS:
    - "web" # DO NOT CHANGE

GITHUB:
    REPOSITORY: /Heimdall-ssh-keys/
    SECRET: # The secret that was used while making the webhook
    OAUTHTOKEN: # OAuth Token generated in the Fourth step

SERVERSIDE:
    SECRET: # A secret that will be used by Heimdall to verify requests from different Servers internally

SLACK: # URL to the Slack API listening to Heimdall's Webhook.